#!/bin/sh
#
# @name lr7pro
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.1081
param set-default CA_ROTOR0_PY 0.1059
param set-default CA_ROTOR0_KM  0.012817

param set-default CA_ROTOR1_PX -0.1040
param set-default CA_ROTOR1_PY -0.1062
param set-default CA_ROTOR1_KM  0.012817

param set-default CA_ROTOR2_PX 0.1081
param set-default CA_ROTOR2_PY -0.1062
param set-default CA_ROTOR2_KM -0.012817

param set-default CA_ROTOR3_PX -0.1040
param set-default CA_ROTOR3_PY 0.1059
param set-default CA_ROTOR3_KM -0.012817

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default BAT1_SOURCE -1

param set-default MAV_SYS_ID $((px4_instance+1))
param set-default UXRCE_DDS_KEY $((px4_instance+1))

param set-default COM_DISARM_PRFLT 0
